### ISSUE TITLE
Read only Genie Page for basic insurance aggregates

### ISSUE THREAD

**Issue by michaelfliegner** [michaelfliegner/BitempWebApp.jl#2]
Web App to display the model created using the API functions.

Pages:
- Listing of contract, partner, tariff ids with links to 
- a page showing a history tree of versions of these entities with links to 
- a page showing the component structure of the entities as of the selected version with links from contracts to partners and tariffs

**Comment by Kaeptenblaubaer** [comment]
Added project

**Comment by michaelfliegner** [comment]
https://github.com/michaelfliegner/BitempWebApp.jl/blob/main/README.md
